### ISSUE TITLE
Design and plan the dashboard frontend essentials

### ISSUE THREAD

**Issue by superdan-t** [BinghamtonRover/rover-control-dashboard#1]
Based on the requirements from Logistics#6, begin designing and planning essential parts of the interface. It need not be fully developed or finalized but we must work towards a prototype.

**Description of Done:**
* Can describe at least one on-screen view
* Know what GUI components are necessary to create the interface
* The implementation is split into multiple concurrent tasks
* Can justify how an implementation of the design supports basic rover operations

Document designs and plans in BookStack

**Comment by Levi-Lesches** [comment]
I propose we start with the main screen for driving because that's the main feature that the old base station was used for. Also it gives us the most time to iterate on the design for probably the most-used feature.

**Comment by Levi-Lesches** [comment]
After meeting with other team leads, I opened more issues for new features. The frontend ones have the label `area: frontend`. Given that, I think we can close this and start working. As for describing the UI, each screen needs: 

1. Camera feeds (#16)
2. Metrics (#22)
3. A readout of controls (#3)

As shown below: 


![Image](https://user-images.githubusercontent.com/20747538/182750828-e217f5ae-6d94-40ea-a863-5ede8f2d754c.png)
